sudo: required
os: linux
language: minimal
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4
services:
  - docker

script:
  - docker version
  - docker build --no-cache --tag lltest/7daystodie --tag lacledeslan/7daystodie-cssource --build-arg BUILDNODE=TravisCI ./linux

notifications:
  slack:
    secure: bQTz1ILVX+UfOcyUo+Tnu/AYmZx2iVIaO000mXoS2Iv2GHkMNW4ip2Y3FShMBJunvMdc471ar57Zo8BYNC3Y3oqNJ+LTiyl9A/cOne/BjFV6PWh0Tnrk9M7XzcJOWzm0gnPxqSFv2qgnSd1kxYH6JxACkuRUttU/ZvYyHMN8rYliPJkL7f6mcFWayTmBtz2tRI+057FzP4yeY6s8gCoXAiBbafvA7M3M/QRA8ECcY3to7w+RTsQhoZ5SxtGDWVjOMzM+dh1m2dG/oSQxrjNp1lG6AANbyBBRBZ56MrX8akRxdeleVJ3PZm6r+dyaRYUY9tT9i8VzB37wKlf+bhNrh46KvV7W3Z6KIQ3AQYj59/CcdM1DsMRzo1wCClLYL+GbQMPTtvU5xRFjPfpWzKaEFD+p20ncv6OhLG05DG+A88+XdR4R5U2VRAOBRn6KeRMpyZn56mwQ5ky6wm0O+4HKerS6bSMtbKQa8UNf+/OB8dmgrJH1/vOsHotNsOa7dsEQL5ZpjlaytTSAVnRGL+SPVAR2x3ymGTNBUdZpgXJeeOdVLZZngBi71ZvGiSangJfewn8rjkq7RBfoTaXlsjJtAmgoLfS9GUu9RZaWhWYCvj5Ai0oUNU/q/DTK1cL4s5rv5s+NPMXrab7oSucAntX9x8X5Ubsi0UBgrVagruR7cE8=

before_deploy:
  - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS";
deploy:
  provider: script
  script: docker push lacledeslan/gamesvr-7daystodie
  on:
    branch: master
after_deploy:
  - curl -X POST https://hooks.microbadger.com/images/lacledeslan/gamesvr-7daystodie/$MICROBADGER_TOKEN
  - sh ./.travis/trigger-travis.sh LacledesLAN gamesvr-7daystodie-freeplay $TRAVIS_ACCESS_TOKEN
