name: linux/amd64

on:
  schedule:
    - cron: '0 14 * * WED'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: Generate ENV Vars
        run: |
          echo "rfc3339_datetime=$(date --rfc-3339=seconds)" >> $GITHUB_ENV
      - name: Build Linux Image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          file: ./linux.Dockerfile
          tags: |
            lacledeslan/gamesvr-7daystodie
            ghcr.io/lacledeslan/gamesvr-7daystodie
          labels: |
            com.lacledeslan.build-node=GitHub (Run #${{ github.run_number }}, ID: ${{ github.run_id }})
            org.opencontainers.image.created=${{ env.rfc3339_datetime }}
            org.opencontainers.image.version=${{ github.sha }}
          pull: true
          no-cache: true
#      TODO: https://github.com/LacledesLAN/gamesvr-7daystodie/issues/1
#      - name: Test Linux Image
#        run: docker run --rm lacledeslan/gamesvr-7daystodie /app/ll-tests/7daystodie.sh
      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Push to Docker HUB
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker push lacledeslan/gamesvr-7daystodie
      - name: Push to GitHub Packages
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker push  ghcr.io/lacledeslan/gamesvr-7daystodie
